---
# file: roles/ansible-common/tasks/setup-Debian.yml

- name: "Debian: Upgrade all packages to the latest version"
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: "{{ common_packages_update_cache | default('false') }}"
  when: common_packages_update_all


- name: "Debian: Install essential packages for some Ansible modules"
  ansible.builtin.apt:
    name: "{{ essential_packages }}"
    state: "{{ essential_packages_state }}"
    update_cache: "yes"
  when: not ansible_check_mode
  tags:
    - install

- name: "Debian: Install common packages for every Linux distribution"
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: "{{ common_packages_state }}"
  when: not ansible_check_mode
  tags:
    - install
