---
# file: roles/ansible-common/tasks/setup-Debian.yml

- name: "Alpine: Upgrade all packages to the latest version"
  community.general.apk:
    upgrade: "yes"
    update_cache: "{{ common_packages_update_cache | default('false') }}"
  when: common_packages_update_all

- name: "Alpine: Install essential packages for some Ansible modules"
  community.general.apk:
    name: "{{ essential_packages }}"
    state: "{{ essential_packages_state }}"
    update_cache: "yes"
  when: not ansible_check_mode
  tags:
    - install

- name: "Alpine: Install common packages for every Linux distribution"
  community.general.apk:
    name: "{{ common_packages }}"
    state: "{{ common_packages_state }}"
  when: not ansible_check_mode
  tags:
    - install
